#!/usr/bin/env python3
"""Write the room icons (icons/<room>.svg, the apps' own home-screen icons) and the marks of the two engines the
Rooms menu also shows (icons/hister.* and icons/searxng.svg) into ui/machiya.css as data URIs, between the ROOM ICONS
markers, so every room shows them from the stylesheet it already loads (no files to serve).
Run after changing an icon: python3 icons/build-css.py"""
import base64
import os
import re

here = os.path.dirname(os.path.abspath(__file__))
css_path = os.path.join(here, "..", "ui", "machiya.css")
rules = []
for room, name, mime in (("shiori", "shiori.svg", "image/svg+xml"), ("konbini", "konbini.svg", "image/svg+xml"),
                         ("niwa", "niwa.svg", "image/svg+xml"), ("kura", "kura.svg", "image/svg+xml"),
                         ("hister", "hister.svg", "image/svg+xml"), ("searxng", "searxng.svg", "image/svg+xml")):
    with open(os.path.join(here, name), "rb") as f:
        data = base64.b64encode(f.read()).decode()
    rules.append('.seal.icon[data-room="%s"] { background-image: url("data:%s;base64,%s"); }' % (room, mime, data))
block = "/* ROOM ICONS (generated by icons/build-css.py from icons/*.svg; don't edit by hand) */\n%s\n/* END ROOM ICONS */" % "\n".join(rules)
css = open(css_path, encoding="utf-8").read()
css, n = re.subn(r"/\* ROOM ICONS .*?/\* END ROOM ICONS \*/", lambda m: block, css, flags=re.S)
if not n:
    raise SystemExit("no ROOM ICONS markers in ui/machiya.css")
open(css_path, "w", encoding="utf-8").write(css)
print("wrote %d room icons into ui/machiya.css" % len(rules))
